/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MemesTableImport } from './routes/memes/table'
import { Route as MemesListImport } from './routes/memes/list'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MemesTableRoute = MemesTableImport.update({
  id: '/memes/table',
  path: '/memes/table',
  getParentRoute: () => rootRoute,
} as any)

const MemesListRoute = MemesListImport.update({
  id: '/memes/list',
  path: '/memes/list',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/memes/list': {
      id: '/memes/list'
      path: '/memes/list'
      fullPath: '/memes/list'
      preLoaderRoute: typeof MemesListImport
      parentRoute: typeof rootRoute
    }
    '/memes/table': {
      id: '/memes/table'
      path: '/memes/table'
      fullPath: '/memes/table'
      preLoaderRoute: typeof MemesTableImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memes/list': typeof MemesListRoute
  '/memes/table': typeof MemesTableRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/memes/list': typeof MemesListRoute
  '/memes/table': typeof MemesTableRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/memes/list': typeof MemesListRoute
  '/memes/table': typeof MemesTableRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/memes/list' | '/memes/table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/memes/list' | '/memes/table'
  id: '__root__' | '/' | '/memes/list' | '/memes/table'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemesListRoute: typeof MemesListRoute
  MemesTableRoute: typeof MemesTableRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemesListRoute: MemesListRoute,
  MemesTableRoute: MemesTableRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/memes/list",
        "/memes/table"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/memes/list": {
      "filePath": "memes/list.tsx"
    },
    "/memes/table": {
      "filePath": "memes/table.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
